homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  unit_system: metric
  time_zone: Australia/Brisbane
  packages: !include_dir_named include
  allowlist_external_dirs: [/config/]
  media_dirs:
    deepstack: /config/www/deepstack/

#default_config:
history:
mobile_app:
sun:
system_health:
cast:
#ffmpeg:
#stream:
media_source:

logger:
  default: warning
  logs:
    homeassistant.components.command_line.sensor: error
    homeassistant.components.rest.sensor: error
    homeassistant.components.websocket_api: fatal
    homeassistant.helpers.service: error
    homeassistant.components.media_player: error
    homeassistant.helpers.entity: error

recorder:
  purge_keep_days: 7
  
hacs:
  token: !secret hacs_token
  options:
    experimental: True

google:
  client_id: !secret google_client_id
  client_secret: !secret google_secret

tts:
  - platform: google_cloud
    key_file: service_account.json
    voice: en-AU-Wavenet-C
    encoding: linear16

browser_mod:
  devices:
    7a0a300c-b4cf495f:
      name: tablet