button_card_templates: !include button_card_templates.yaml
kiosk_mode:
  user_settings:
    - users:
        - "tablet"
      kiosk: true

sidebar:
  title: Sidebar
  clock: false
  digitalClock: true
  digitalClockWithSeconds: false
  date: true
  dateFormat: 'dddd, DD MMMM YYYY'
  twelveHourVersion: true
  period: true
  hideTopMenu: true
  hideHassSideBar: true
  sidebarMenu:
    - action: navigate
      navigation_path: /lovelace-tablet/0
      name: Home
  style: |
    :host {
        --sidebar-background: #2f3233;
        --sidebar-text-color: #fff;
        --face-color: #21353E;
        --face-border-color: #21353E;
        --clock-hands-color: #fff;
        --clock-seconds-hand-color: #fff;
        --clock-middle-background: #21353E;
        --clock-middle-border: #21353E;
        box-shadow: inset -11px 0px 6px 1px #1d1f1f;
    }
    .sidebarMenu li.active {
     background-color: #6A808D!important;
     }

views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .         .       ."
        "sidebar  loungeroom  kitchen   bedroom ."
        "sidebar  ollie       teddy     home    ."
        "sidebar  .           .         .       ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.5)
          grid-template-columns: 0 repeat(2, 1fr) 0fr
          grid-template-rows: 0 repeat(4, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .        ."
            ".  sidebar     sidebar  ."
            ".  loungeroom  kitchen  ."
            ".  bedroom     teddy    ."
            ".  ollie       home     ."
            ".  .           .        ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0fr
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .       ."
            "sidebar  loungeroom  bedroom ."
            "sidebar  kitchen     teddy   ."
            "sidebar  ollie       home    ."
            "sidebar  .           .       ."
    cards:

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: markdown
        view_layout:
          grid-area: sidebar
        content: |
          {% set attributes = states.sensor.template_sidebar.attributes | default %}
          {% for template in attributes %}
          {{ state_attr('sensor.template_sidebar', template) }}
          {% endfor %}
      
      - type: vertical-stack
        cards:
          - type: custom:button-card
            name: Home
            icon: mdi:home
            template: navigation
          
          - type: custom:button-card
            name: Security
            icon: mdi:shield-home
            template: navigation
          
          - type: custom:button-card
            name: Media
            icon: mdi:play-circle
            template: navigation
          
          - type: custom:button-card
            name: Weather
            icon: mdi:cloud
            template: navigation
      
        
      - type: grid
        view_layout:
          grid-area: sidebar
        cards:
          - type: button
            icon: mdi:robot-vacuum
            #tap_action:

          - type: button
            icon: mdi:information-outline
            tap_action:
              !include lovelace/views/popup/admin.yaml

          - type: button
            icon: mdi:arrow-up-bold-circle-outline
            #tap_action:

      #################################################
      #                                               #
      #                  LOUNGE ROOM                  #
      #                                               #
      #################################################

      - type: grid
        title: Lounge Room
        view_layout:
          grid-area: loungeroom
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.kitchen_pendants #hue_group
            name: Pendants
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.kitchen_downlight
            name: Lamp
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: media_player.lounge_room_tv
            name: Tv
            hold_action:
              !include lovelace/views/popup/lounge_room_tv.yaml
            template:
              - base
              - icon_tv
              - loader

      #################################################
      #                                               #
      #                    Kitchen                    #
      #                                               #
      #################################################

      - type: grid
        title: Kitchen
        view_layout:
          grid-area: kitchen
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.kitchen_pendant_lights
            name: Pendants
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.kitchen_downlight #hue_group
            name: Downlight
            template:
              - light
              - icon_spot

          - type: custom:button-card
            entity: media_player.kitchen_display
            template:
              - conditional_media
              - icon_nest_mini


      #################################################
      #                                               #
      #                    BEDROOM                    #
      #                                               #
      #################################################

      - type: grid
        title: Bedroom
        view_layout:
          grid-area: bedroom
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.bedroom_lamps #hue_group
            name: Lamps
            template:
              - light
              - icon_lamp

          - type: custom:button-card
            entity: media_player.bedroom_speaker
            template:
              - conditional_media
              - icon_nest_mini

          - type: custom:button-card
            entity: media_player.bedroom_tv
            name: "TV"
            hold_action:
              !include lovelace/views/popup/bedroom_tv.yaml
            template:
              - base
              - icon_tv
              - loader

      #################################################
      #                                               #
      #                    OLLIE                      #
      #                                               #
      #################################################

      - type: grid
        title: Ollie
        view_layout:
          grid-area: ollie
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.ollie_s_lamp #hue_group
            name: Lamp
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: media_player.ollie_s_room_speaker
            template:
              - conditional_media
              - icon_nest_mini
          
          - type: custom:button-card
            entity: climate.ollie_room
            name: AC
            template: climate

      #################################################
      #                                               #
      #                    TEDDY                      #
      #                                               #
      #################################################

      - type: grid
        title: Teddy
        view_layout:
          grid-area: teddy
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.teddy_s_lamp #hue_group
            name: Lamp
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: media_player.teddy_s_room_speaker
            template:
              - conditional_media
              - icon_nest_mini
          
          - type: custom:button-card
            entity: climate.teddy_room
            show_icon: true
            name: AC
            template: climate

      #################################################
      #                                               #
      #                     HOME                      #
      #                                               #
      #################################################

      - type: grid
        title: Home
        view_layout:
          grid-area: home
        columns: 2
        cards:

          - type: custom:button-card
            entity: person.william
            name: William
            tap_action:
              !include lovelace/views/popup/home_william.yaml
            hold_action:
              action: none
            template: person

          - type: custom:button-card
            entity: person.emily
            name: Emily
            tap_action:
              !include lovelace/views/popup/home_emily.yaml
            hold_action:
              action: none
            template: person

          - type: custom:button-card
            name: cameras
            icon: mdi:cctv
            show_state: false
            tap_action: !include lovelace/views/popup/cameras.yaml
            #template: base

          - type: custom:button-card
            name: Security
            icon: mdi:shield-home
            show_state: false
            tap_action: !include lovelace/views/popup/alarm_panel.yaml
            #template: base
          
          #- type: custom:button-card
          #  entity: script.home_leave
          #  name: Leaving
          #  hold_action:
          #    action: none
          #  template:
          #    - base
          #    - icon_away

          #- type: custom:button-card
          #  entity: script.home_arrive
          #  name: Home
          #  hold_action:
          #    action: none
          #  template:
          #    - base
          #    - icon_home