button_card_templates:
  standard_button:
    styles:
      card:
        - font-size: 10px
      icon:
        - width: 30%
      name:
        - font-size: 12px
      state:
        - justify-self: start
        - font-size: 10px
        - padding: 0px 5px
  
  light:
    hold_action: &light_action
      action: fire-dom-event
      browser_mod:
        command: popup
        title: '[[[ return entity.attributes.friendly_name ]]]'
        deviceID: this
        card:
          type: entities
          entities:
            - type: custom:light-popup-card
              entity: '[[[ return entity.entity_id ]]]'
              icon: none
              fullscreen: false
              brightnessWidth: 130px
              brightnessHeight: 360px
              borderRadius: 1.7em
              sliderColor: '#c7c7c7'
              sliderTrackColor: rgba(25, 25, 25, 0.9)
              actionSize: 4.5em
              actionsInARow: 2
              displayType: slider
              actions:
                - service: light.turn_on
                  service_data:
                    entity_id: '[[[ return entity.entity_id ]]]'
                    color_temp: 153
                  color: "#d8d9e1"
                - service: light.turn_on
                  service_data:
                    entity_id: '[[[ return entity.entity_id ]]]'
                    color_temp: 326
                  color: "#d5b08d"
                - service: light.turn_on
                  service_data:
                    entity_id: '[[[ return entity.entity_id ]]]'
                    color_temp: 500
                  color: "#ce944b"
                - service: browser_mod.popup
                  service_data:
                    title: '[[[ return entity.attributes.friendly_name ]]]'
                    deviceID: this
                    card:
                      type: entities
                      show_header_toggle: false
                      entities:
                        - entity: '[[[ return entity.entity_id ]]]'
                          secondary_info: last-changed
                        - type: custom:light-entity-card
                          entity: '[[[ return entity.entity_id ]]]'
                          brightness: false
                          color_temp: true
                          full_width_sliders: true
                          hide_header: true
                          show_slider_percent: true
                          smooth_color_wheel: true
                          consolidate_entities: true

background: center / cover no-repeat fixed  url('/local/bg_long.png?v=1')
title: Home
kiosk_mode:
  mobile_settings:
    hide_header: true
views:
  - title: Home
    panel: true
    path: home_view
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: 'custom:mod-card'
            card_mod:
              style:
                swipe-card:
                  $: |
                    .swiper-pagination-bullet {
                      width: 10px;
                      height: 10px;
                      background-color: rgba(255,255,255,1.0) !important;
                      position: relative;
                      top: 15px
                    }
                    .swiper-pagination-bullet-active {
                      background-color: rgba(247,148,29,1.0) !important;
                    }
            card:
              type: 'custom:swipe-card'
              start_card: 1
              reset_after: 30
              parameters:
                spaceBetween: 8
                autoHeight: true
                pagination:
                  type: bullets
              cards:
                - type: markdown
                  content: >
                    <table> <tr><td width="200px"><h3>{{
                    states('sensor.dashboard_greeting') }}, {{ user
                    }}</h3><strong>Current Temperature:</strong>
                    {{state_attr('weather.home','temperature') |
                    round}}&deg;C</br> {% if is_state("sun.sun",
                    "above_horizon") -%}
                        <strong>Next Sunset:</strong> {{as_timestamp(strptime(state_attr("sun.sun", "next_setting"), '')) | timestamp_custom("%-I:%M %p")}}
                    {%- else -%}
                        <strong>Next Sunrise:</strong> {{as_timestamp(strptime(state_attr("sun.sun", "next_rising"), '')) | timestamp_custom("%-I:%M %p")}}
                    {%- endif %}</br></br><strong>SmartHome Mode:</strong> {{
                    states('input_select.home_mode') }}</br>
                    <strong>Active Devices:</strong> {{
                    states('sensor.dashboard_active') }}
                    </td><td></br><img
                    src="https://darksky.net/{{states('sensor.dashboard_weather')}}"
                    width="190px" /></td></tr> <tr><td colspan="2">{{
                    states('sensor.dashboard_occupancy')
                    }}</td></tr></table></br>
                  style: |
                    ha-card {
                      background: transparent;
                      margin-top: -15px;
                      margin-bottom: -7px;
                    }
                - type: picture-glance
                  aspect_ratio: '16:9'
                  camera_image: camera.front_door
                  camera_view: live
                  entities: []
                  name: Front Door
                  card_mod:
                    style: |
                      ha-card {
                        margin-bottom: 15px;
                        background: rgba(255, 255, 255, 0.0);
                        border-radius: 0;
                        box-shadow: none;
                        color: white;
                       }
                      .box {
                        background: rgba(255,255,255,0) !important;
                      }
                
          - type: 'custom:homekit-card'
            home: false
            title: Home
            useBrightness: true
            useTemperature: true
            titleColor: '#FFF'
            statePositionTop: true
            style: |
              :host {
                --tile-background: rgba(255, 255, 255, 0.10);
                --tile-border-radius: 12px;
                --tile-width: 100px;
                --tile-height: 100px;
                --tile-on-background: rgba(255, 255, 255, 0.7);

                --tile-name-text-color: rgba(255, 255, 255, 0.8);
                --tile-on-name-text-color: rgba(0, 0, 0, 1);

                --tile-state-text-color: rgba(255, 255, 255, 0.8);
                --tile-on-state-text-color: rgba(0, 0, 0, 1);

                --tile-state-changed-text-color: rgb(134, 134, 134);
                --tile-unavailable-state-text-color: rgba(255, 255, 255, 1);

                --tile-value-text-color: rgba(255, 0, 0, 1);


                --tile-icon-color: rgba(255, 255, 255, 0.8);
                --tile-on-icon-color: rgba(247,148,29,0.9) !important;
                /* #f7d959; rgba(255,204,110,1.0) */
                font-family: Arial;
              }
              .top-fav {
                background-color: rgba(255, 255, 230,0.5) !important;
              }
              .off-bg {
                background-color: rgba(255, 255, 255, 0.10) ;
              }
              .fan .icon {
                color: rgba(0, 0, 0, 0.5) !important;
              }
              .hideState .state {
                visibility:hidden !important;
              }
              homekit-button .icon.climate {
                 background-color: rgba(247,148,29,1.0) !important;
              }
            entities:
              - title: Favorites
                entities:
                  - card: 'custom:button-card'
                    conditionalClass: |
                      [[[ 
                        return "top-fav";
                      ]]]
                    type: 'custom:light-popup-card'
                    tap_action: !include lovelace/views/popup/alarm_panel.yaml
                    hold_action:
                      action: none
                    cardOptions:
                      name: Alarm & Security
                      icon: 'mdi:shield-home'
                      size: 80%
                      show_name: false
                      show_state: false
                      show_label: false
                      styles:
                        card:
                          - '-webkit-box-shadow': none
                          - box-shadow: none
                          - background-color: 'rgba(255, 255, 255, 0.0)'
                          - margin-top: 5px
                        icon:
                          - color: |
                              [[[ 
                                if (states['alarm_control_panel.home_alarm'].state == "disarmed")
                                  return "rgba(51, 102, 0,1)";
                                return "rgba(230, 0, 0,0.7)";
                              ]]]  
                  - card: 'custom:button-card'
                    tap_action: !include lovelace/views/popup/ollie_meds.yaml
                    hold_action:
                      action: none
                    conditionalClass: |
                      [[[ 
                        return "top-fav";
                      ]]]
                    cardOptions:
                      name: Ollie's Meds
                      icon: 'mdi:pill'
                      size: 80%
                      show_name: false
                      show_state: false
                      show_label: false
                      styles:
                        card:
                          - '-webkit-box-shadow': none
                          - box-shadow: none
                          - background-color: 'rgba(255, 255, 255, 0.0)'
                          - margin-top: 5px
                        icon:
                          - color: |
                              [[[ 
                                if (states['input_boolean.morning_meds_taken'].state == "on") and (states['input_boolean.evening_meds_taken'].state == "on") and (states['input_boolean.bedtime_meds_taken'].state == "on")
                                  return "green";
                                return "white";
                              ]]]
                  - card: 'custom:button-card'
                    conditionalClass: |
                      [[[ 
                        return "top-fav";
                      ]]]
                    tap_action: !include lovelace/views/popup/cameras.yaml
                    hold_action:
                      action: none
                    cardOptions:
                      name: Cameras
                      icon: 'mdi:cctv'
                      size: 90%
                      show_name: false
                      show_state: false
                      show_label: false
                      styles:
                        card:
                          - box-shadow: none
                          - background-color: 'rgba(255, 255, 255, 0.0)'
                          - margin-top: '-5px'
                        icon:
                          - color: white
                  - entity: light.kitchen_pendant_lights
                    name: Kitchen Island
                    icon: 'mdi:wall-sconce-round'
                    double_tap_action:
                      action: popup
                  - entity: light.ollie_s_lamp
                    name: Ollie's Lamp
                    icon: 'mdi:lamp'
                    double_tap_action:
                      action: popup
                  - entity: light.teddy_s_lamp
                    name: Teddy's Lamp
                    icon: 'mdi:wall-sconce-round-variant'
                    double_tap_action:
                      action: popup
              - title: Lights
                entities:
                  - entity: light.kitchen_pendant_lights
                    name: Kitchen Island
                    icon: 'mdi:wall-sconce-round'
                    double_tap_action:
                      action: popup
                  - entity: light.kitchen_downlight
                    name: Kitchen Downlight
                    icon: 'mdi:wall-sconce-round'
                    double_tap_action:
                      action: popup
                  - entity: light.bedroom_lamps
                    name: Bedroom Lamps
                    icon: 'mdi:lamp'
                    double_tap_action:
                      action: popup
                  - entity: light.ollie_s_lamp
                    name: Ollie's Lamp
                    icon: 'mdi:lamp'
                    double_tap_action:
                      action: popup
                  - entity: light.teddy_s_lamp
                    name: Teddy's Lamp
                    icon: 'mdi:wall-sconce-round-variant'
                    double_tap_action:
                      action: popup
              - title: Media
                entities:
                  - entity: media_player.emily_ytube_music
                    name: Em's Music
                    icon: 'mdi:music-circle-outline'
                    tap_action: !include lovelace/views/popup/em_music.yaml
                    hold_action:
                      action: none
                  - entity: media_player.will_ytube_music
                    name: Will's Music
                    icon: 'mdi:music-circle-outline'
                    tap_action: !include lovelace/views/popup/will_music.yaml
                    hold_action:
                      action: none
              #- title: Cleaning
              #  entities:            
                  #- entity: sensor.arturito
                  #  name: Vacuum
                  #  icon: 'mdi:robot-vacuum'
                  #  state: vacuum.arturito
                  #  statePath: attributes.battery_level
                  #  offStates:
                  #    - docked
                  #  spin: true
                  #  tap_action:
                  #    action: navigate
                  #    navigation_path: /sub-vacuum/0
                  #  hold_action:
                  #    action: none
              - title: Climate
                entities:
                  - entity: climate.bedroom
                    name: A/C
                    icon: 'mdi:air-conditioner'
                    offStates:
                      - "off"
                    tap_action: !include lovelace/views/popup/bedroom_ac.yaml
                    hold_action:
                      action: popup
                  - entity: climate.teddy_room
                    name: A/C
                    icon: 'mdi:air-conditioner'
                    offStates:
                      - "off"
                    tap_action: !include lovelace/views/popup/teddy_ac.yaml
                    hold_action:
                      action: popup
                  - entity: climate.ollie_room
                    name: A/C
                    icon: 'mdi:air-conditioner'
                    offStates:
                      - "off"
                    tap_action: !include lovelace/views/popup/ollie_ac.yaml
                    hold_action:
                      action: popup
                  - entity: input_boolean.dummy
                    name: Admin
                    icon: 'mdi:tools'
                    tap_action: !include lovelace/views/popup/admin.yaml
                    hold_action:
                      action: none
                    conditionalClass: |
                      [[[ 
                        return "hideState";
                      ]]]
                    hide: |
                      [[[ 
                        if (user.name == "William")
                         return false;
                        else
                         return true;
                      ]]]