
binary_sensor:

    ####################################################
    #                                                  #
    #                      BINARY                      #
    #                                                  #
    ####################################################


  - platform: ping
    host: 8.8.8.8
    name: server_internet_access
  

  - platform: mqtt
    name: "Front Door Motion"
    state_topic: "home/frontdoor/camera/motion"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: motion


  - platform: template
    sensors:
      fullykiosk_motion:
        friendly_name: Camera
        icon_template: mdi:camera
        value_template: >
          {{ not is_state_attr('sensor.fullykiosk', 'motionDetectorState', 0) }}

      night_mode:
        friendly_name: Night Mode
        value_template: >-
          {{ is_state('switch.adaptive_lighting_sleep_mode_teddy_s_room', 'on') 
            or is_state('switch.adaptive_lighting_sleep_mode_ollie_s_room', 'on') }}

      morning_meds_taken:
        friendly_name: Morning Meds Taken
        value_template: >-
          {% if is_state('input_boolean.morning_meds_taken', 'on') %}
            Yes
          {% else %}
            No
          {% endif %}

      evening_meds_taken:
        friendly_name: Evening Meds Taken
        value_template: >-
          {% if is_state('input_boolean.evening_meds_taken', 'on') %}
            Yes
          {% else %}
            No
          {% endif %}

      bedtime_meds_taken:
        friendly_name: Bedtime Meds Taken
        value_template: >-
          {% if is_state('input_boolean.bedtime_meds_taken', 'on') %}
            Yes
          {% else %}
            No
          {% endif %}

      bedroom_presence:
        unique_id: "bedroom-presence-template-sensor"
        friendly_name: "Bedroom Presence"
        device_class: "presence"
        value_template: "{{ is_state('sensor.pixel_4xl_room_presence', 'bedroom') }}"

sensor:

    ####################################################
    #                                                  #
    #                     SENSORS                      #
    #                                                  #
    ####################################################

  - platform: version
    name: hass_version_installed

  - platform: version
    name: hass_version_latest
    source: docker

  - platform: version
    name: hass_version_latest_beta
    beta: true
    source: docker

  - platform: filesize
    file_paths:
      - /config/home-assistant_v2.db
      - /config/home-assistant.log

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  - platform: uptime

  - platform: time_date
    display_options:
      ['time', 'date']

  - platform: rest
    name: hass_release_notes
    resource: https://api.github.com/repos/home-assistant/core/releases/latest
    value_template: '{{ value_json.name }}'
    json_attributes: [body]
    scan_interval: 21600

  - platform: dnsip

  - platform: darksky
    api_key: !secret darksky_key
    language: en
    mode: daily
    monitored_conditions:
      ['precip_probability', 'temperature', 'apparent_temperature']

  #- platform: rest
  #  name: fullykiosk
  #  json_attributes:
  #    ['batteryLevel', 'screenBrightness', 'plugged', 'motionDetectorState', 
  #    'lastAppStart', 'internalStorageFreeSpace', 'internalStorageTotalSpace', 
  #    'ramFreeMemory', 'ramTotalMemory', 'currentFragment']
  #  resource: !secret fullykiosk_rest_resource
  #  value_template: '{{ value_json.isScreenOn }}'
  #  scan_interval: 10

  - platform: plex_recently_added
    name: Recently Added Movies # will create sensor.recently_added_movies
    token: !secret plex_token
    host: !secret plex_host
    port: 32400
    section_types:
    - movie

  - platform: plex_recently_added
    name: Recently Added TV  # will create sensor.recently_added_tv
    token: !secret plex_token
    host: !secret plex_host
    port: 32400
    section_types:
    - show
  
  - platform: plex_recently_added
    name: Recently Added
    token: !secret plex_token
    host: !secret plex_host
    port: 32400
    max: 1
    image_resolution: 500


    ####################################################
    #                                                  #
    #                   COMMAND LINE                   #
    #                                                  #
    ####################################################

  

    ####################################################
    #                                                  #
    #                     TEMPLATE                     #
    #                                                  #
    ####################################################

  - platform: scrape
    name: Dashboard Weather
    resource: !secret darksky_forecast
    select: "img"
    attribute: "src"
    index: 5
    scan_interval: 900